import {
    Alert,
    Animated,
    BackHandler,
    Button,
    Dimensions,
    Easing,
    findNodeHandle,
    FlatList,
    Image,
    ImageBackground,
    Keyboard,
    KeyboardAvoidingView,
    Linking,
    Modal,
    Platform,
    ScrollView,
    Share,
    StyleSheet,
    Switch,
    TextInput,
    TouchableHighlight,
    TouchableOpacity,
    UIManager,
    View
} from 'react-native';

import {
    BoldText,
    BoldTextComponent,
    CaptionComponent as Caption,
    ErrorTextComponent,
    HeadlineComponent as Headline,
    Label,
    SubheadingComponent as Subheading,
    TextComponent as Text,
    TextComponent,
    TitleComponent as Title
} from './Text';
import {ActivityIndicator, FAB} from 'react-native-paper'
import theme from '../utilities/styling';
import Icon from 'react-native-vector-icons/Ionicons';

export {
    TextComponent,
    theme,
    Switch,
    Share,
    ImageBackground,
    BoldTextComponent,
    FlatList,
    ScrollView,
    ErrorTextComponent,
    Animated,
    Easing,
    Keyboard,
    View,
    Icon,
    UIManager,
    Image,
    TextInput,
    Text,
    Title,
    Headline,
    Subheading,
    Caption,
    BoldText,
    Alert,
    TouchableHighlight,
    TouchableOpacity,
    Linking,
    StyleSheet,
    findNodeHandle,
    Label,
    Dimensions,
    ActivityIndicator,
    KeyboardAvoidingView,
    Modal,
    Platform,
    FAB,
    Button,
    BackHandler,
};
